language: php

php:
    - 5.3
    - 5.4

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1
    - WP_VERSION=3.7 WP_MULTISITE=0
    - WP_VERSION=3.7 WP_MULTISITE=1

before_script:
  - pear config-set preferred_state beta
  - yes '' | pecl install apcu
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION 

script: phpunit
